#!/bin/sh
if [ "$1" = "low" ]; then
	notify-send -u low "Niski poziom baterii" "Powinieneś zmienić baterię lub podłączyć sprzęt do ładowania, aby nie utracić swojej pracy."
elif [ "$1" = "critical" ]; then
	notify-send -u critical "Krytyczny poziom baterii" "Powinieneś natychmiast zmienić baterię lub podłączyć sprzęt do ładowania, aby nie utracić swojej pracy."
fi
