/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_main16.gif */
extern const unsigned char res_ico_main16[];

/* created by reswrap from file res/img_banner.gif */
extern const unsigned char res_img_banner[];

