/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[]={
   71, 73, 70, 56, 55, 97, 16,  0, 16,  0,
  240,  0,  0,255,  0,  0,255,255,255, 44,
    0,  0,  0,  0, 16,  0, 16,  0,  0,  2,
   32,140,143,169,187,160,222, 30, 76, 19,
  213,  3,110,200,241, 53,168, 49,155,232,
  145, 38, 38,114, 88,168, 90,217,251,158,
  178, 89,  0,  0, 59
  };

