/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_check.gif */
extern const unsigned char res_ico_check[];

/* created by reswrap from file res/ico_main16.gif */
extern const unsigned char res_ico_main16[];

/* created by reswrap from file res/ico_main32.gif */
extern const unsigned char res_ico_main32[];

/* created by reswrap from file res/ico_uncheck.gif */
extern const unsigned char res_ico_uncheck[];

/* created by reswrap from file res/ico_user16.gif */
extern const unsigned char res_ico_user16[];

/* created by reswrap from file res/ico_user32.gif */
extern const unsigned char res_ico_user32[];

/* created by reswrap from file res/img_banner.gif */
extern const unsigned char res_img_banner[];

