/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/rdelay.gif */
extern const unsigned char resico_rdelay[];

/* created by reswrap from file res/rrate.gif */
extern const unsigned char resico_rrate[];

