/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/volume2k.gif */
extern const unsigned char resico_volume2k[];

/* created by reswrap from file res/volumexp.png */
extern const unsigned char resico_volumexp[];

