.PHONY: clean uninstall install

CC = gcc
CXX = g++

CFLAGS = -Wall -c
CXXFLAGS = -Wall -c

PREFIX = /usr/local


# for non developers, do not touch this
CFLAGS += -D UHEXE_VERSION="0.0.1" -c --std=c99
CXXFLAGS += `fox-config --cflags` -c --std=c++98 -fpic -D_COMCTL32_BUILDING
LDFLAGS += `fox-config --libs`

OUTPUT = libctl32.so
VERSION = 0.0.1

#COBJECTS = $(CSOURCES:.c=.o)

CXXSOURCES = comctl32.cpp I2KComboBox.cpp I2KListBox.cpp
CXXOBJECTS = $(CXXSOURCES:.cpp=.o)


OBJECTS = $(CXXOBJECTS) $(COBJECTS)

all: $(OUTPUT)

# link executable
$(OUTPUT): $(OBJECTS)
	$(CXX) $(OBJECTS) -shared -o $@ $(LDFLAGS)

clean:
	rm -f $(OBJECTS) $(OUTPUT)

install: all
	mkdir -p $(PREFIX)/include/ice2k
	cp I2KComboBox.h $(PREFIX)/include/ice2k/
	cp I2KListBox.h $(PREFIX)/include/ice2k/
	cp comctl32.h $(PREFIX)/include/ice2k/
	rm -f $(PREFIX)/lib/$(OUTPUT)
	cp $(OUTPUT) $(PREFIX)/lib/$(OUTPUT)

uninstall:
	rm $(PREFIX)/include/ice2k/I2KComboBox.h || true
	rm $(PREFIX)/include/ice2k/I2KListBox.h || true
	rm $(PREFIX)/include/ice2k/comctl32.h || true
	rmdir $(PREFIX)/include/ice2k >/dev/null 2>&1 || true
	rm -f $(PREFIX)/lib/$(OUTPUT) || true

